=== vulnerability-lookup/vulnerability-lookup/website/web/api/v1/schemas/cve/create-full-cve-record-request.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "type": "object",
    "properties": {
        "containers": {
            "type": "object",
            "required": [
                "cna"
            ],
            "properties": {
                "cna": {
                    "type": "object",
                    "required": [
                        "affected",
                        "descriptions",
                        "providerMetadata",
                        "references"
                    ],
                    "properties": {
                        "affected": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "vendor": {
                                        "type": "string"
                                    },
                                    "product": {
                                        "type": "string"
                                    },
                                    "versions": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "version": {
                                                    "type": "string"
                                                },
                                                "status": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "descriptions": {
                            "type": "array",
                            "required": [
                                "lang",
                                "value"
                            ],
                            "items": {
                                "type": "object",
                                "properties": {
                                    "lang": {
                                        "type": "string"
                                    },
                                    "value": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "problemTypes": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "descriptions": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "description": {
                                                    "type": "string"
                                                },
                                                "lang": {
                                                    "type": "string"
                                                },
                                                "type": {
                                                    "type": "string"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "providerMetadata": {
                            "type": "object",
                            "properties": {
                                "orgId": {
                                    "type": "string"
                                },
                                "shortName": {
                                    "type": "string"
                                },
                                "dateUpdated": {
                                    "type": "string",
                                    "format": "date-time"
                                }
                            }
                        },
                        "references": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "tags": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "url": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "dateAssigned": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "datePublic": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "title": {
                            "type": "string"
                        },
                        "impacts": {
                            "type": "array"
                        },
                        "metrics": {
                            "type": "array"
                        },
                        "configurations": {
                            "type": "array"
                        },
                        "workarounds": {
                            "type": "array"
                        },
                        "solutions": {
                            "type": "array"
                        },
                        "exploits": {
                            "type": "array"
                        },
                        "timeline": {
                            "type": "array"
                        },
                        "credits": {
                            "type": "array"
                        },
                        "source": {
                            "type": "string"
                        },
                        "tags": {
                            "type": "array"
                        },
                        "taxonomyMappings": {
                            "type": "array"
                        }
                    }
                }
            }
        },
        "cveMetadata": {
            "type": "object",
            "properties": {
                "assignerOrgId": {
                    "type": "string"
                },
                "cveId": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "assignerShortName": {
                    "type": "string"
                },
                "requesterUserId": {
                    "type": "string"
                },
                "dateReserved": {
                    "type": "string"
                },
                "datePublished": {
                    "type": "string"
                }
            }
        },
        "dataType": {
            "type": "string"
        },
        "dataVersion": {
            "type": "string"
        }
    }
}

=== vulnerability-lookup/vulnerability-lookup/website/web/api/v1/schemas/cve/published-cve-example.json
{
    "containers": {
        "cna": {
            "affected": [
                {
                    "vendor": "string",
                    "product": "string",
                    "versions": [
                        {
                            "version": "string",
                            "status": "string"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "string",
                    "value": "string"
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "string",
                            "lang": "string",
                            "type": "string"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "string",
                "shortName": "string",
                "dateUpdated": "2022-05-13T14:26:39.293Z"
            },
            "references": [
                {
                    "name": "string",
                    "tags": [
                        "string"
                    ],
                    "url": "string"
                }
            ]
        }
    },
    "cveMetadata": {
        "assignerOrgId": "string",
        "cveId": "string",
        "state": "string",
        "assignerShortName": "string",
        "requesterUserId": "string",
        "dateReserved": "string",
        "datePublished": "string"
    },
    "dataType": "string",
    "dataVersion": "string"
}
